/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jrame._phanhoanghuy_t8;

import java.awt.List;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import static java.util.Collections.list;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListModel;

/**
 *
 * @author huyph
 */
public class bai11 extends javax.swing.JFrame {

    /**
     * Creates new form bai11
     */
    public bai11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_sc = new javax.swing.JButton();
        btn_sl = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_ngto = new javax.swing.JButton();
        btn_boto = new javax.swing.JButton();
        btn_tong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_nhap = new javax.swing.JButton();
        txt_nhap = new javax.swing.JTextField();
        chb_am = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_ptu = new javax.swing.JList<>();
        btn_dong = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Thao tác trên JList - Checkbox");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Chọn tác vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btn_sc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sc.setText("Tô đen số chẵn");
        btn_sc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_scMouseClicked(evt);
            }
        });

        btn_sl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sl.setText("Tô đen số lẻ");
        btn_sl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_slMouseClicked(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setText("Xóa các giá trị đang tô đen");
        btn_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaMouseClicked(evt);
            }
        });

        btn_ngto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ngto.setText("Tô đen số nguyên tố");
        btn_ngto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ngtoMouseClicked(evt);
            }
        });

        btn_boto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_boto.setText("Bỏ tô đen");
        btn_boto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_botoMouseClicked(evt);
            }
        });

        btn_tong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tong.setText("Tổng giá trị trong JList");
        btn_tong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_xoa)
                    .addComponent(btn_tong)
                    .addComponent(btn_boto)
                    .addComponent(btn_ngto)
                    .addComponent(btn_sl)
                    .addComponent(btn_sc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_sc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_sl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_ngto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_boto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_tong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Nhập thông tin:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btn_nhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_nhap.setText("Nhập");
        btn_nhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nhapMouseClicked(evt);
            }
        });

        txt_nhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nhapKeyPressed(evt);
            }
        });

        chb_am.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chb_am.setText("Cho nhập số âm");

        jScrollPane1.setViewportView(list_ptu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(btn_nhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chb_am))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nhap)
                    .addComponent(txt_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chb_am))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        btn_dong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_dong.setText("Đóng chương trình");
        btn_dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_dong)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(btn_dong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dongMouseClicked
        // TODO add your handling code here:
        JOptionPane.showOptionDialog(rootPane, "Bạn chắc chắn muốn thoát.", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,null, EXIT_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_btn_dongMouseClicked

    public void NhapAm(char kt){
        if (chb_am.isSelected()){
            if (kt != '-')
                txt_nhap.setEditable(false);
            else txt_nhap.setEditable(true);
        }
            
    }
    
    private void txt_nhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nhapKeyPressed
        // TODO add your handling code here:
        char kt = evt.getKeyChar();
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
//            btn_nhap.doClick();
        if (chb_am.isSelected()){
            if (!Character.isDigit(kt) && !Character.isISOControl(kt) && kt != '-'){
                txt_nhap.setEditable(false);
            }
            else
                txt_nhap.setEditable(true);
        }
        else{
            if (!Character.isDigit(kt) && !Character.isISOControl(kt))
                txt_nhap.setEditable(false);
            else
                txt_nhap.setEditable(true);
        }
        
    }//GEN-LAST:event_txt_nhapKeyPressed
    
    
    ArrayList<Integer> arrInt = new ArrayList<>();
    public void CapnhatList(){
        // Tạo DefaultListModel để quản lý dữ liệu cho JList
        DefaultListModel listInt = new DefaultListModel<>();
        // thêm ptu vào DLM
        for (int i: arrInt)
            listInt.addElement(i);
        // thêm add DLM vào JList
        list_ptu.setModel(listInt);
    }
    
    private void btn_nhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nhapMouseClicked
        try{
            int ptu = Integer.parseInt(txt_nhap.getText());
            // kiểm tra ptu đã tồn tại hay chưa
            for (int i: arrInt){
                if (ptu == i){
                    JOptionPane.showMessageDialog(rootPane, "Đã tồn tại giá trị trong bảng.");
                    txt_nhap.setText("");
                    txt_nhap.requestFocus();
                    return;
                }
            }
            arrInt.add(ptu);
            CapnhatList();
            txt_nhap.setText("");
            txt_nhap.requestFocus();
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Bạn nhập sai giá trị !!!");
            txt_nhap.requestFocus();
        }
        
        
        
        
    }//GEN-LAST:event_btn_nhapMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        txt_nhap.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void btn_scMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_scMouseClicked
        // TODO add your handling code here:
        try{
            // bỏ tô đen
            list_ptu.clearSelection();
            for (int i=0; i<arrInt.size(); i++){
                if (arrInt.get(i) % 2 == 0) {
                    // tô đen các ptu JList tại vị trí i
                    list_ptu.addSelectionInterval(i,i);
                }
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Da co loi !");
        }
    }//GEN-LAST:event_btn_scMouseClicked

    private void btn_slMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_slMouseClicked
        // TODO add your handling code here:
        try{
            // bỏ tô đen
            list_ptu.clearSelection();
            for (int i=0; i<arrInt.size(); i++){
                if (arrInt.get(i) % 2 != 0) {
                    // tô đen các ptu JList tại vị trí i
                    list_ptu.addSelectionInterval(i,i);
                }
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Da co loi !");
        }
    }//GEN-LAST:event_btn_slMouseClicked

    public boolean KTNgto(int n){
        if (n<=0 || n == 1) return false;
        for (int i=2; i <= Math.sqrt(n); i++){
            if (n % i == 0){
                return false;
            }
        }
        return true;
    }
    
    private void btn_ngtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ngtoMouseClicked
        // TODO add your handling code here:
        try{
            // bỏ tô đen
            list_ptu.clearSelection();
            for (int i=0; i<arrInt.size(); i++){
                if (KTNgto(arrInt.get(i))) {
                    // tô đen các ptu JList tại vị trí i
                    list_ptu.addSelectionInterval(i,i);
                }
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Da co loi !");
        }
        
    }//GEN-LAST:event_btn_ngtoMouseClicked

    private void btn_botoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_botoMouseClicked
        // TODO add your handling code here:
        // bỏ tô đen
        list_ptu.clearSelection();
    }//GEN-LAST:event_btn_botoMouseClicked

    private void btn_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaMouseClicked
        // TODO add your handling code here:
        if (list_ptu.getSelectedIndex() != -1){
            int[] a = list_ptu.getSelectedIndices();
            // Sắp xếp mảng các vị trí giảm dần để xóa từ cuối lên đầu
            Arrays.sort(a);
            // Xóa các phần tử được chọn từ cuối lên đầu
            for (int i = a.length-1; i>=0; i--)
                arrInt.remove(a[i]);
            CapnhatList();
        }
        else 
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn giá trị muốn xóa !");
        
    }//GEN-LAST:event_btn_xoaMouseClicked

    private void btn_tongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tongMouseClicked
        // TODO add your handling code here:
        if (arrInt.isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Không có phần tử trong list");
        else{
            int tong=0;
            for (int i: arrInt)
                tong += i;
            JOptionPane.showMessageDialog(rootPane, "Tổng giá trị phần tử trong List = "+tong);
        }
    }//GEN-LAST:event_btn_tongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_boto;
    private javax.swing.JButton btn_dong;
    private javax.swing.JButton btn_ngto;
    private javax.swing.JButton btn_nhap;
    private javax.swing.JButton btn_sc;
    private javax.swing.JButton btn_sl;
    private javax.swing.JButton btn_tong;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JCheckBox chb_am;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> list_ptu;
    private javax.swing.JTextField txt_nhap;
    // End of variables declaration//GEN-END:variables
}
