/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jrame._phanhoanghuy_t8;

import javax.swing.JOptionPane;

/**
 *
 * @author huyph
 */
public class bai12 extends javax.swing.JFrame {

    /**
     * Creates new form bai12
     */
    public bai12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_nhap = new javax.swing.JLabel();
        btn_nhap = new javax.swing.JButton();
        txt_n = new javax.swing.JTextField();
        btn_luu = new javax.swing.JButton();
        txt_ptu = new javax.swing.JTextField();
        btn_xuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("XỬ LÝ MẢNG");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Số phần tử");

        lbl_nhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nhap.setText("Nhập phần tử");

        btn_nhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nhap.setForeground(new java.awt.Color(0, 0, 153));
        btn_nhap.setText("NHẬP");
        btn_nhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nhapMouseClicked(evt);
            }
        });

        txt_n.setText("              ");
        txt_n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nKeyPressed(evt);
            }
        });

        btn_luu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_luu.setForeground(new java.awt.Color(0, 0, 153));
        btn_luu.setText("LƯU");
        btn_luu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_luuMouseClicked(evt);
            }
        });

        txt_ptu.setText("                  ");
        txt_ptu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ptuKeyPressed(evt);
            }
        });

        btn_xuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xuat.setForeground(new java.awt.Color(204, 0, 0));
        btn_xuat.setText("XUẤT");
        btn_xuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_xuat)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(lbl_nhap)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ptu, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(txt_n))
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_nhap, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_luu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btn_nhap)
                    .addComponent(txt_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_nhap)
                        .addComponent(txt_ptu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_luu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_xuat)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nKeyPressed
        char kt = evt.getKeyChar();
        if (!Character.isDigit(kt) && !Character.isISOControl(kt) ){
            txt_n.setEditable(false);
        }
        else txt_n.setEditable(true);
        
    }//GEN-LAST:event_txt_nKeyPressed

    private void txt_ptuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ptuKeyPressed
        char kt = evt.getKeyChar();
        if (!Character.isDigit(kt) && !Character.isISOControl(kt) && kt != '-' && kt != '.'){
            txt_ptu.setEditable(false);
        }
        else txt_ptu.setEditable(true);
        
    }//GEN-LAST:event_txt_ptuKeyPressed
    static int n;
    static double[] arr;
    static int d;
    private void btn_nhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nhapMouseClicked
        // TODO add your handling code here:
        d=0;
        n = Integer.parseInt(txt_n.getText());
        txt_ptu.setEnabled(true);
        btn_luu.setEnabled(true);
        lbl_nhap.setText("Nhập phần tử "+(d+1));
        txt_ptu.requestFocus();
        arr = new double[n];
    }//GEN-LAST:event_btn_nhapMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txt_n.setText("");
        
        txt_ptu.setEnabled(false);
        btn_luu.setEnabled(false);
        btn_xuat.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened
    
    private void btn_luuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_luuMouseClicked
        // TODO add your handling code here:
        try {
            int ptu = Integer.parseInt(txt_ptu.getText().trim());
            if (d == n-1){
                arr[d] = ptu;
                JOptionPane.showMessageDialog(rootPane, "Hoàn thành nhập phần tử");
                txt_ptu.setEnabled(false);
                txt_ptu.setText("");
                btn_luu.setEnabled(false);
            }
            else{
                arr[d] = ptu;
                lbl_nhap.setText("Nhập phần tử "+(d+2));
                d++;
                txt_ptu.setText("");
                txt_ptu.requestFocus();
            }
        } catch(Exception ex){
            lbl_nhap.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn nhập sai giá trị !!!");
        }
        btn_xuat.setEnabled(true);
        
        
    }//GEN-LAST:event_btn_luuMouseClicked

    private void btn_xuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xuatMouseClicked
        // TODO add your handling code here:
        String s="";
        for (int i=0; i<n; i++){
            s += arr[i]+", ";
        }
        JOptionPane.showMessageDialog(rootPane, "Mảng sau khi nhập "+s);
    }//GEN-LAST:event_btn_xuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_nhap;
    private javax.swing.JButton btn_xuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_nhap;
    private javax.swing.JTextField txt_n;
    private javax.swing.JTextField txt_ptu;
    // End of variables declaration//GEN-END:variables
}
