/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jrame._phanhoanghuy_jrame;

/**
 *
 * @author huyph
 */
public class bai1 extends javax.swing.JFrame {

    /**
     * Creates new form bai1
     */
    public bai1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_a = new javax.swing.JTextField();
        txt_b = new javax.swing.JTextField();
        btn_cong = new javax.swing.JButton();
        btn_tru = new javax.swing.JButton();
        btn_nhan = new javax.swing.JButton();
        btn_chia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_ketqua = new javax.swing.JTextField();
        lab_loi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("bai 1");
        setName("bai1"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nhập số A:");

        jLabel2.setText("Nhập số B:");

        txt_a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_aKeyPressed(evt);
            }
        });

        txt_b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_bKeyPressed(evt);
            }
        });

        btn_cong.setText("Cộng");
        btn_cong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_congMouseClicked(evt);
            }
        });

        btn_tru.setText("Trừ");
        btn_tru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_truMouseClicked(evt);
            }
        });

        btn_nhan.setText("Nhân");
        btn_nhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nhanMouseClicked(evt);
            }
        });

        btn_chia.setText("Chia");
        btn_chia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_chiaMouseClicked(evt);
            }
        });

        jLabel3.setText("Kết quả:");

        lab_loi.setForeground(new java.awt.Color(255, 0, 0));
        lab_loi.setText("lỗi");
        lab_loi.setName("lab_loi"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cong)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tru)
                        .addGap(18, 18, 18)
                        .addComponent(btn_nhan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_chia))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_b)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ketqua, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lab_loi))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cong)
                            .addComponent(btn_nhan)
                            .addComponent(btn_chia)
                            .addComponent(btn_tru)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ketqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab_loi)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_aKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_aKeyPressed
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())){
            txt_a.setEditable(false);
        }
        else txt_a.setEditable(true);
    }//GEN-LAST:event_txt_aKeyPressed

    private void txt_bKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bKeyPressed
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())){
            txt_b.setEditable(false);
        }
        else txt_b.setEditable(true);
    }//GEN-LAST:event_txt_bKeyPressed

    private void btn_congMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_congMouseClicked
        int a = Integer.parseInt(txt_a.getText());
        int b = Integer.parseInt(txt_b.getText());
        int tong = a+b;
        txt_ketqua.setText(""+tong);
        lab_loi.setVisible(false);
    }//GEN-LAST:event_btn_congMouseClicked

    private void btn_truMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_truMouseClicked
        int a = Integer.parseInt(txt_a.getText());
        int b = Integer.parseInt(txt_b.getText());
        txt_ketqua.setText(""+(a-b));
        lab_loi.setVisible(false);
    }//GEN-LAST:event_btn_truMouseClicked

    private void btn_nhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nhanMouseClicked
        int a = Integer.parseInt(txt_a.getText());
        int b = Integer.parseInt(txt_b.getText());
        txt_ketqua.setText(""+(a*b));
        lab_loi.setVisible(false);
    }//GEN-LAST:event_btn_nhanMouseClicked

    private void btn_chiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_chiaMouseClicked
        int a = Integer.parseInt(txt_a.getText());
        int b = Integer.parseInt(txt_b.getText());
        try{
            txt_ketqua.setText(""+(a/b));
        }
        catch(Exception ex){
            lab_loi.setVisible(true);
            lab_loi.setText("Không thể chia cho 0");
            
        }
    }//GEN-LAST:event_btn_chiaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lab_loi.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chia;
    private javax.swing.JButton btn_cong;
    private javax.swing.JButton btn_nhan;
    private javax.swing.JButton btn_tru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lab_loi;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_b;
    private javax.swing.JTextField txt_ketqua;
    // End of variables declaration//GEN-END:variables
}
