/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jrame.onthi;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import javax.swing.JOptionPane;

/**
 *
 * @author huyph
 */
public class bai1 extends javax.swing.JFrame {

    /**
     * Creates new form bai1
     */
    public bai1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ms = new javax.swing.JTextField();
        txt_ht = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_hsl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbb_qq = new javax.swing.JComboBox<>();
        btn_kiemtra = new javax.swing.JButton();
        btn_nhaplai = new javax.swing.JButton();
        btn_themfile = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN NHÂN SỰ");

        jLabel2.setText("Mã số nhân sự");

        txt_ms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_msKeyPressed(evt);
            }
        });

        txt_ht.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_htKeyPressed(evt);
            }
        });

        jLabel3.setText("Họ tên nhân sự");

        txt_hsl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_hslKeyPressed(evt);
            }
        });

        jLabel4.setText("Hệ số lương");

        jLabel5.setText("Nơi sinh");

        cbb_qq.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbb_qq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cần thơ", "Vĩnh Long", "Trà Vinh", "Đồng Tháp", "Sài Gòn" }));

        btn_kiemtra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_kiemtra.setText("KIỂM TRA");
        btn_kiemtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kiemtraMouseClicked(evt);
            }
        });

        btn_nhaplai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_nhaplai.setText("NHẬP LẠI");
        btn_nhaplai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nhaplaiMouseClicked(evt);
            }
        });

        btn_themfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_themfile.setText("THÊM VÀO FILE");
        btn_themfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themfileMouseClicked(evt);
            }
        });

        btn_thoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_thoat.setText("THOÁT");
        btn_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_thoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addComponent(btn_kiemtra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_nhaplai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_themfile))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_ms, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_ht, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbb_qq, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_hsl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_thoat)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(txt_ht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(txt_hsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(cbb_qq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kiemtra)
                    .addComponent(btn_nhaplai)
                    .addComponent(btn_themfile)
                    .addComponent(btn_thoat))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thoatMouseClicked
        // TODO add your handling code here:
        // dong chuong trinh
        System.exit(0);
        
        
    }//GEN-LAST:event_btn_thoatMouseClicked

    private void txt_msKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_msKeyPressed
        char kt = evt.getKeyChar();
        if (!Character.isDigit(kt) && !Character.isLetter(kt) && !Character.isISOControl(kt))
            txt_ms.setEditable(false);
        else txt_ms.setEditable(true);
        
        
    }//GEN-LAST:event_txt_msKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txt_ms.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void txt_htKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_htKeyPressed
        // TODO add your handling code here:
        char kt = evt.getKeyChar();
        if (!Character.isLetter(kt) && !Character.isISOControl(kt) && kt != ' ')
            txt_ht.setEditable(false);
        else txt_ht.setEditable(true);
    }//GEN-LAST:event_txt_htKeyPressed

    private void txt_hslKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hslKeyPressed
        // TODO add your handling code here:
        char kt = evt.getKeyChar();
        if (!Character.isDigit(kt) && !Character.isISOControl(kt) && kt != '-' && kt != '.')
            txt_hsl.setEditable(false);
        else txt_hsl.setEditable(true);
        
    }//GEN-LAST:event_txt_hslKeyPressed

    private void btn_kiemtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kiemtraMouseClicked
        // TODO add your handling code here:
        String text = txt_ms.getText();
        if (text.length() != 6){
            JOptionPane.showMessageDialog(rootPane, "Ma so nhan su phai nhap du 6 ky tu");
            txt_ms.requestFocus();
            return;
        }
        if (txt_ht.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Khong duoc bo trong ho ten nhan su");
            txt_ht.requestFocus();
            return;
        }
        try {
            double hsl = Double.parseDouble(txt_hsl.getText());
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "ban nhap sai he so luong");
            txt_hsl.requestFocus();
            return;
        }
        
    }//GEN-LAST:event_btn_kiemtraMouseClicked

    private void btn_nhaplaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nhaplaiMouseClicked
        // TODO add your handling code here:
        txt_ms.setText("");
        txt_ht.setText("");
        txt_hsl.setText("");
        txt_ms.requestFocus();
    }//GEN-LAST:event_btn_nhaplaiMouseClicked

    public static String Inhoa(String s){
        StringBuilder result = new StringBuilder();
        String[] words = s.split("\\s+"); // Tách chuỗi thành các từ bằng khoảng trắng

        for (String word : words) {
            if (!word.isEmpty()) {
                char firstChar = Character.toUpperCase(word.charAt(0)); // Chuyển ký tự đầu thành chữ hoa
                String restOfWord = word.substring(1); // Lấy phần còn lại của từ

                result.append(firstChar).append(restOfWord).append(" "); // Ghép từ đã được viết hoa vào kết quả
            }
        }
        return result.toString().trim(); // Trả về chuỗi kết quả sau khi đã loại bỏ dấu cách thừa
    
    }
    
    private void btn_themfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themfileMouseClicked
        // TODO add your handling code here:
        try {
            FileWriter f = new FileWriter("d:\\nhansu.txt",true);
            f.write(txt_ms.getText()+"\n");
            String ht = txt_ht.getText();
            f.write(Inhoa(ht)+"\n");
            f.write(txt_hsl.getText()+"\n");
            f.write(cbb_qq.getSelectedItem()+"\n");
            f.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, "Da xay ra loi!!!");
        }
        
        
    }//GEN-LAST:event_btn_themfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kiemtra;
    private javax.swing.JButton btn_nhaplai;
    private javax.swing.JButton btn_themfile;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JComboBox<String> cbb_qq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_hsl;
    private javax.swing.JTextField txt_ht;
    private javax.swing.JTextField txt_ms;
    // End of variables declaration//GEN-END:variables
}
