/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jrame.onthi;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author huyph
 */
public class bai2 extends javax.swing.JFrame {

    /**
     * Creates new form bai2
     */
    public bai2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ms = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_giaban = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbb_nsx = new javax.swing.JComboBox<>();
        btn_kiemtra = new javax.swing.JButton();
        btn_nhaplai = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN MẶT HÀNG");

        jLabel2.setText("Mã số mặt hàng");

        jLabel3.setText("Tên mặt hàng");

        jLabel4.setText("Giá bán");

        jLabel5.setText("Số lượng");

        jLabel6.setText("Nhà SX");

        cbb_nsx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbb_nsx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vĩnh Lợi", "VLUTE", "Oshi", "Lays", "Toni" }));

        btn_kiemtra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_kiemtra.setText("KIỂM TRA");
        btn_kiemtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kiemtraMouseClicked(evt);
            }
        });

        btn_nhaplai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_nhaplai.setText("NHẬP LẠI");
        btn_nhaplai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nhaplaiMouseClicked(evt);
            }
        });

        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setText("THÊM VÀO FLIE");
        btn_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMouseClicked(evt);
            }
        });

        btn_thoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_thoat.setText("THOÁT");
        btn_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_thoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_kiemtra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_nhaplai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_thoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ms, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbb_nsx, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                                .addComponent(txt_soluong, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_giaban, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_ms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_giaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbb_nsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kiemtra)
                    .addComponent(btn_nhaplai)
                    .addComponent(btn_them)
                    .addComponent(btn_thoat))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thoatMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_thoatMouseClicked

    private void btn_kiemtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kiemtraMouseClicked
        // TODO add your handling code here:
        String ms = txt_ms.getText();
        String ten = txt_ten.getText();
        if (!Character.isLetter(ms.charAt(0)) || !Character.isLetter(ms.charAt(1))){
            JOptionPane.showMessageDialog(rootPane, "2 ký tự đầu phải là chữ cái", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txt_ms.requestFocus();
        }
        else if (ten.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "khong dc bo trong ten", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txt_ten.requestFocus();
        }
        else {
            try {
                int gb = Integer.parseInt(txt_giaban.getText());
                if (gb <= 0){
                    JOptionPane.showMessageDialog(rootPane, "gia ban chi nhap so duong", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    txt_giaban.requestFocus();
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "gia ban chi nhap so duong", "Thông báo", JOptionPane.WARNING_MESSAGE);
                txt_giaban.requestFocus();
            }
            try {
                int sl = Integer.parseInt(txt_soluong.getText());
                if (sl <= 0){
                    JOptionPane.showMessageDialog(rootPane, "so luong chi nhap so duong", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    txt_soluong.requestFocus();
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "so luong chi nhap so duong", "Thông báo", JOptionPane.WARNING_MESSAGE);
                txt_soluong.requestFocus();
            }
        }
        
    }//GEN-LAST:event_btn_kiemtraMouseClicked

    private void btn_nhaplaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nhaplaiMouseClicked
        // TODO add your handling code here:
        txt_ms.setText("");
        txt_ten.setText("");
        txt_giaban.setText("");
        txt_soluong.setText("");
        cbb_nsx.setSelectedIndex(0);
        
    }//GEN-LAST:event_btn_nhaplaiMouseClicked

    private void btn_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseClicked
        // TODO add your handling code here:
        try{
            FileWriter f = new FileWriter("d:\\mathang.txt",true);
            f.write(txt_ms.getText()+"\n");
            f.write(txt_ten.getText()+"\n");
            f.write(txt_giaban.getText()+"\n");
            f.write(txt_soluong.getText()+"\n");
            f.write(cbb_nsx.getSelectedItem()+"\n");
            f.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, "ghi ko thanh cong!");
        }
        
        
    }//GEN-LAST:event_btn_themMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kiemtra;
    private javax.swing.JButton btn_nhaplai;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JComboBox<String> cbb_nsx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_giaban;
    private javax.swing.JTextField txt_ms;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables
}
